repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5 # Use the latest stable version
    hooks:
      # Run the linter with auto-fixing
      - id: ruff
        args: [--fix]
      # Run the code formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1 # Use the latest stable version
    hooks:
      - id: mypy
        additional_dependencies: [
                  "types-requests",
                  "pydantic",
                  "selenium",
                  "allure-python-commons==2.16.0",
                  "pydantic==2.13.4"
                ]
